apiVersion: v1
kind: Service
metadata:
  name: coco-test
  namespace: prod
  labels:
          app: coco-test
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: coco-test
