apiVersion: v1
kind: Service
metadata:
  name: coco-test-flask
  namespace: prod
  labels:
          app: coco-test-flask
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: coco-test-flask
